services:
  cliente:
    build:
      context: .
      args:
        VITE_API_URL: https://administrado-zuma-main-afg1p6.laravel.cloud/api
    container_name: cliente_sakai
    ports:
      - "5174:5174"
    networks:
      - laravel_red_2025