services:
  cliente:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost/api
    container_name: cliente_sakai
    ports:
      - "5174:5174"
    networks:
      - laravel_red_2025

networks:
  laravel_red_2025:
    external: true
